"""add memory typ

Revision ID: cb0172c2c6d2
Revises: 2c109e0af786
Create Date: 2024-11-12 14:41:34.291267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0172c2c6d2'
down_revision: Union[str, None] = '2c109e0af786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'type')
    # ### end Alembic commands ###
