"""Create audio data table1

Revision ID: 61b19f93594f
Revises: 2c500e0cf7ec
Create Date: 2024-11-08 16:51:01.687478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b19f93594f'
down_revision: Union[str, None] = '2c500e0cf7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audio_data_music_id_fkey', 'audio_data', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('audio_data_music_id_fkey', 'audio_data', 'music_data', ['music_id'], ['id'])
    # ### end Alembic commands ###
