"""Create audio data table

Revision ID: 809e3ba87868
Revises: e2cf81da1548
Create Date: 2024-11-08 16:42:49.909191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '809e3ba87868'
down_revision: Union[str, None] = 'e2cf81da1548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('music_id', sa.Uuid(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['music_data.id'], ),
    sa.PrimaryKeyConstraint('id', name='audio_pkey')
    )
    op.create_index('audio_user_idx', 'audio_data', ['music_id'], unique=False)
    op.drop_column('music_data', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_data', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_index('audio_user_idx', table_name='audio_data')
    op.drop_table('audio_data')
    # ### end Alembic commands ###
