"""Create music table

Revision ID: 840cf0878f18
Revises: 
Create Date: 2024-11-08 11:19:27.727967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840cf0878f18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_data', sa.Column('lyric', sa.TEXT(), nullable=True))
    op.add_column('music_data', sa.Column('image', sa.TEXT(), nullable=True))
    op.add_column('music_data', sa.Column('data', sa.LargeBinary(), nullable=False))
    op.add_column('music_data', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('music_data', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('music_data', 'song_name',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('music_data', 'artist',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               nullable=True)
    op.create_index('music_user_idx', 'music_data', ['song_id', 'created_at', 'artist', 'song_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('music_user_idx', table_name='music_data')
    op.alter_column('music_data', 'artist',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('music_data', 'song_name',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('music_data', 'updated_at')
    op.drop_column('music_data', 'created_at')
    op.drop_column('music_data', 'data')
    op.drop_column('music_data', 'image')
    op.drop_column('music_data', 'lyric')
    # ### end Alembic commands ###
