"""add music table format

Revision ID: e2cf81da1548
Revises: 840cf0878f18
Create Date: 2024-11-08 14:14:13.732430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cf81da1548'
down_revision: Union[str, None] = '840cf0878f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_data', sa.Column('format', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_data', 'format')
    # ### end Alembic commands ###
